SRCDIR = src
INCLUDEDIR = include

SRCFILENAMES = main.cpp

SRCFILEPATHS = $(addprefix $(SRCDIR)/, $(SRCFILENAMES))

CXXFLAGS := $(CXXFLAGS)

mpm.x: $(SRCFILEPATHS)
	g++ -o $@ $^ -I$(INCLUDEDIR) $(CXXFLAGS)
